---
- name: Workstation setup
  hosts: localhost

  vars_files:
    - vars/main.yml

  pre_tasks:
    - include_vars: "vars/{{ ansible_hostname }}.yml"
      tags:
      - install
      - install-asdf
      - configuration
      - configure-mpd

  roles:
    - role: aur
      tags: aur
    - role: install
      tags: install
    - role: configuration
      tags: configuration
    - role: dotfiles
      tags: dotfiles
