---
- name: Workstation setup
  hosts: localhost

  vars_files:
    - vars/main.yml
    - "vars/{{ ansible_os_family | lower }}.yml"

  tasks:
    - include: "tasks/{{ ansible_os_family | lower }}.yml"

    - name: Create directories
      file:
        dest: "{{ item }}"
        state: directory
      with_items:
        - "{{ ansible_user_dir }}/bin"
        - "{{ ansible_user_dir }}/scripts"

    - name: Create .xinitrc
      template:
        src: templates/xinitrc.j2
        dest: "{{ ansible_user_dir }}/.xinitrc"
        mode: 0644

    - name: Fetch dotfiles
      git:
        repo: ssh://git@github.com/mtpereira/dotfiles.git
        dest: "{{ ansible_user_dir }}/.dotfiles"
        version: master
        accept_hostkey: yes

    - name: Install rbenv
      git:
        repo: https://github.com/rbenv/rbenv.git
        dest: "{{ ansible_user_dir }}/.rbenv"
        version: master
        accept_hostkey: yes

    - name: Fetch oh-my-zsh installer
      get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: /tmp/oh-my-zsh.sh
        mode: 0755

    - name: Install oh-my-zsh
      command: /tmp/oh-my-zsh.sh
      args:
        creates: "{{ ansible_user_dir }}/.oh-my-zsh"

    - name: Install dotfiles
      command: "{{ ansible_user_dir }}/.dotfiles/install.sh"

    - name: Copy wallpaper
      copy:
        src: files/wallpaper.png
        dest: "{{ wallpaper_path }}"
        mode: 0644

    - name: Setup wallpaper with feh
      command: feh --bg-fill {{ wallpaper_path }}

# TODO
# - Add ohmyzsh
# - Add powerline fonts https://github.com/powerline/fonts
# - Add vpn script
# - Fix fonts on i3 (persistent xset)
# - Fix fonts on urxvt
# - Add automount of USB volumes
# - Fix bash_+ naming
# - Install pip and pip packages
# - Install and configure minikube
# - Install and configure kubelet

