---
- name: Workstation setup
  hosts: localhost

  vars_files:
    - vars/main.yml

  roles:
    - role: aur
      tags: aur
    - role: install
      tags: install
    - role: configuration
      tags: configuration
    - role: dotfiles
      tags: dotfiles
