---
- name: Workstation setup
  hosts: localhost

  vars_files:
    - vars/main.yml

  roles:
    - role: install
      tags: install
    - role: configuration
      tags: configuration
    - role: dotfiles
      tags: dotfiles
    - role: firewall
      become: yes
      tags: firewall

# TODO
# - Add powerline fonts https://github.com/powerline/fonts
# - Fix bash_+ naming
# - Add fstrim.timer service

