---
- name: Configure system
  include: tasks/system.yml

- name: Configure user
  include: tasks/user.yml

- name: Configure mpd and ncmpcpp
  include: tasks/mpd.yml
  when: configuration_mpd_enabled

- name: Configure network
  include: tasks/network.yml

- name: Setup bluetooth
  include: tasks/bluetooth.yml
