---
- name: Create directories
  file:
    dest: "{{ item }}"
    state: directory
  with_items: "{{ configuration_user_dirs }}"

- name: Change user shell
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ configuration_user_shell }}"

- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes

- name: Enable lightdm
  systemd:
    name: lightdm
    enabled: yes
  become: yes

- name: Enable devmon from udevil package
  systemd:
    name: "devmon@{{ ansible_user_id }}"
    enabled: yes
    state: started
  become: yes

- name: Disable wall messages from systemd ask password tool
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - systemd-ask-password-wall.service
    - systemd-ask-password-wall.path
  become: yes

- name: Configure .xsession
  template:
    src: templates/xsession.j2
    dest: "{{ ansible_user_dir }}/.xsession"
    mode: 0755

- name: Configure xorg keyboard rules
  copy:
    src: files/xorg-keyboard.conf
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    mode: 0644
  become: yes

- name: Configure xorg touchpad rules
  copy:
    src: files/xorg-touchpad.conf
    dest: /etc/X11/xorg.conf.d/00-touchpad.conf
    mode: 0644
  become: yes

- name: Configure logind
  copy:
    src: files/logind.conf
    dest: /etc/systemd/logind.conf
    mode: 0644
  become: yes

- name: Configure systemd
  block:
    - name: Create systemd conf directory
      file:
        dest: /etc/systemd/system.conf.d
        state: directory

    - name: Configure timeouts
      copy:
        src: files/systemd-timeout.conf
        dest: /etc/systemd/system.conf.d/00-timeout.conf
        mode: 0644
  become: yes

- name: Copy wallpaper
  copy:
    src: files/wallpaper.png
    dest: "{{ configuration_wallpaper_path }}"
    mode: 0644

- name: Configure vconsole.conf
  template:
    src: templates/vconsole.conf.j2
    dest: /etc/vconsole.conf
    mode: 0644
  become: yes

- name: Configure mpd and ncmpcpp
  block:
    - name: Create mpd directories
      file:
        path: "{{ ansible_user_dir }}/.config/mpd/playlists"
        state: directory

    - name: Create mpd configuration file
      template:
        src: templates/mpd.conf.j2
        dest: "{{ ansible_user_dir }}/.config/mpd/mpd.conf"
        mode: 0644

    - name: Enable mpd
      systemd:
        name: "mpd"
        user: yes
        enabled: yes
        state: started

    - name: Configure ncmpcpp
      block:
        - file:
            dest: "{{ ansible_user_dir }}/.ncmpcpp/"
            mode: 0755
            state: directory

        - template:
            src: templates/ncmpcpp.config.j2
            dest: "{{ ansible_user_dir }}/.ncmpcpp/config"
            mode: 0644
  when: configuration_mpd_enabled

- name: Enable dropbox
  systemd:
    name: dropbox
    user: yes
    enabled: yes
    state: started

- name: Enable fstrim service
  systemd:
    name: fstrim.timer
    enabled: yes
    state: started
  become: yes

- name: Enable systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: yes
    state: started
  become: yes

- name: Configure resolvers from systemd-resolved
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolve.conf
    force: yes
    state: link
  become: yes

- name: Enable redshift
  systemd:
    name: redshift
    user: yes
    enabled: yes
    state: started

- name: Enable systemd-timesyncd
  command: timedatectl set-ntp on
  become: yes

- name: Enable coloured output for pacman tools
  replace:
    path: /etc/pacman.conf
    regexp: '^#Color$'
    replace: 'Color'
  become: yes
  when: configuration_pacman_colour

- name: Disable IPv6
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_file: "/etc/sysctl.d/ipv6.conf"
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  become: yes
