---
- name: Configure system
  include_tasks: tasks/system.yml
  tags: configure-system

- name: Configure user
  include_tasks: tasks/user.yml
  tags: configure-user

- name: Configure mpd and ncmpcpp
  include_tasks: tasks/mpd.yml
  when: configuration_mpd_enabled
  tags: configure-mpd

- name: Configure network
  include_tasks: tasks/network.yml
  tags: configure-network

- name: Setup bluetooth
  include_tasks: tasks/bluetooth.yml
  tags: configure-bluetooth
