---
- name: Configure DNS
  block:
    - name: Configure dnsmasq
      copy:
        src: files/network/dnsmasq.conf
        dest: /etc/dnsmasq.conf
        mode: 0644
        owner: root

    - name: Configure resolv.conf for dnsmasq
      copy:
        src: files/network/resolv.conf
        dest: /etc/resolv.conf
        owner: root
        mode: 0644

    - name: Enable and reload dnsmasq
      systemd:
        name: dnsmasq
        enabled: yes
        state: restarted

    - name: Configure dhcpcd
      copy:
        src: files/network/dhcpcd.conf
        dest: /etc/dhcpcd.conf
        mode: 0644
        owner: root

    - name: Load dhcpcd configuration
      systemd:
        name: dhcpcd
        state: restarted
  become: yes

- name: Install and setup maza
  block:
    - set_fact:
        configuration_maza_path: "{{ ansible_user_dir }}/bin/maza"

    - name: Install maza
      copy:
        src: files/network/maza.sh
        dest: "{{ configuration_maza_path }}"
        mode: 0755

    - name: Configure maza blacklist
      command: "{{ configuration_maza_path }} start"
      become: yes

    - name: Reload dnsmasq
      systemd:
        name: dnsmasq
        state: reloaded
      become: yes

- name: Disable IPv6
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_file: "/etc/sysctl.d/ipv6.conf"
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  become: yes

- name: Block incoming connections
  block:
    - name: Reset ufw
      ufw:
        state: reset
    - name: Deny incoming connections
      ufw:
        default: deny
        direction: incoming
        log: no
        state: enabled
    - name: Enable ufw
      systemd:
        name: ufw
        scope: system
        enabled: yes
        state: started
  become: yes
