---
- name: Enable lightdm
  systemd:
    name: lightdm
    enabled: yes
  become: yes

- name: Enable devmon from udevil package
  systemd:
    name: "devmon@{{ ansible_user_id }}"
    enabled: yes
    state: started
  become: yes

- name: Disable wall messages from systemd ask password tool
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - systemd-ask-password-wall.service
    - systemd-ask-password-wall.path
  become: yes

- name: Configure logind
  copy:
    src: files/system/logind.conf
    dest: /etc/systemd/logind.conf
    mode: 0644
  become: yes

- name: Configure systemd
  block:
    - name: Create systemd conf directory
      file:
        dest: /etc/systemd/system.conf.d
        state: directory

    - name: Configure timeouts
      copy:
        src: files/system/systemd-timeout.conf
        dest: /etc/systemd/system.conf.d/00-timeout.conf
        mode: 0644
  become: yes

- name: Configure vconsole.conf
  template:
    src: templates/vconsole.conf.j2
    dest: /etc/vconsole.conf
    mode: 0644
  become: yes

- name: Enable fstrim service
  systemd:
    name: fstrim.timer
    enabled: yes
    state: started
  become: yes

- name: Enable systemd-timesyncd
  command: timedatectl set-ntp on
  become: yes

- name: Enable coloured output for pacman tools
  replace:
    path: /etc/pacman.conf
    regexp: '^#Color$'
    replace: 'Color'
  become: yes
  when: configuration_pacman_colour

- name: Configure journald retention policy
  block:
    - name: Create the journald.conf.d directory
      file:
        path: /etc/systemd/journald.conf.d
        state: directory
        mode: 0755
        owner: root

    - name: Add configuration file
      copy:
        src: files/system/journald-rotation.conf
        dest: /etc/systemd/journald.conf.d/rotation.conf
        mode: 0644

    - name: Restart journald
      systemd:
        name: systemd-journald
        state: restarted
        enabled: yes
        scope: system
  become: yes

- name: Configure xorg keyboard rules
  copy:
    src: files/system/xorg-keyboard.conf
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    mode: 0644
  become: yes

- name: Configure xorg touchpad rules
  copy:
    src: files/system/xorg-touchpad.conf
    dest: /etc/X11/xorg.conf.d/00-touchpad.conf
    mode: 0644
  become: yes

- name: Disable DPMS
  copy:
    src: files/system/xorg-dpms.conf
    dest: /etc/X11/xorg.conf.d/10-dpms.conf
    mode: 0644
  become: yes
  when: configuration_system_dpms_disabled

- name: Configure Logitech webcam zoom
  copy:
    src: files/system/99-logitech-default-zoom.rules
    dest: /etc/udev/rules.d/
    owner: root
    mode: 0644
  become: yes

- name: Enable thermald
  systemd:
    name: thermald
    state: started
    enabled: yes
  become: yes

- name: Fan control
  become: true
  block:
    - name: Install utilities
      community.general.pacman:
        name:
          - dell-bios-fan-control-git
          - i8kutils
          - lm_sensors
          - thermald
    - name: Enable lm_sensors
      ansible.builtin.systemd:
        name: lm_sensors
        state: started
        enabled: true
    - name: Configure fancontrol
      ansible.builtin.copy:
        src: files/system/fancontrol
        dest: /etc/fancontrol
        owner: root
        mode: "0644"
    - name: Enable fancontrol
      ansible.builtin.systemd:
        name: fancontrol
        state: started
        enabled: true
    - name: Keep fancontrol running after resume
      block:
        - name: Setup system resume unit
          ansible.builtin.copy:
            src: files/system/root-resume.service
            dest: /etc/systemd/system/root-resume.service
            owner: root
            mode: "0644"
        - name: Enable system resume service
          ansible.builtin.systemd:
            name: root-resume
            state: started
            enabled: true
            daemon-reload: true
    - name: Disable BIOS control
      ansible.builtin.command: dell-bios-fan-control 0
      register: configuration_dell_bios_fan_control
      changed_when: true
