---
- name: Create vconsole.conf
  template:
    src: templates/vconsole.conf.j2
    dest: /etc/vconsole.conf
    mode: 0644
  become: yes

- name: Get mirrorlist
  uri:
    url: https://www.archlinux.org/mirrorlist/
    method: POST
    body: "country=all&protocol=https&ip_version=4&use_mirror_status=on"
    return_content: yes
  register: pacman_mirrorlist

- name: Create mirrorlist
  copy:
    content: "{{ pacman_mirrorlist.content | regex_replace('#Server =', 'Server =') }}"
    dest: /etc/pacman.d/mirrorlist
    mode: 0644
  become: yes

- name: Install packages
  pacman:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ packages }}"
  become: yes

- name: Fetch zoom client package
  get_url:
    url: https://zoom.us/client/latest/zoom_x86_64.pkg.tar.xz
    dest: /tmp/zoom_x86_64.pkg.tar.xz
    mode: 0644

- name: Install zoom client
  command: pacman -U --noconfirm /tmp/zoom_x86_64.pkg.tar.xz
  become: yes

- name: Create mpd directories
  file:
    path: "{{ ansible_user_dir }}/.config/mpd/playlists"
    state: directory

- name: Create mpd configuration file
  template:
    src: templates/mpd.conf.j2
    dest: "{{ ansible_user_dir }}/.config/mpd/mpd.conf"
    mode: 0644

- name: Enable mpd
  systemd:
    name: "mpd"
    user: yes
    enabled: yes
    state: started

- name: Configure ncmpcpp
  template:
    src: templates/ncmpcpp.config.j2
    dest: "{{ ansible_user_dir }}/.ncmpcpp/config"
    mode: 0644

- name: Enable lightdm
  systemd:
    name: lightdm
    enabled: yes
  become: yes

- name: Enable devmon from udevil package
  systemd:
    name: "devmon@{{ ansible_user_id }}"
    enabled: yes
    state: started
  become: yes

