---
- name: Create vconsole.conf
  template:
    src: templates/vconsole.conf.j2
    dest: /etc/vconsole.conf
    mode: 0644
  become: yes

- name: Get mirrorlist
  uri:
    url: https://www.archlinux.org/mirrorlist/
    method: POST
    body: "country=all&protocol=https&ip_version=4&use_mirror_status=on"
    return_content: yes
  register: pacman_mirrorlist

- name: Create mirrorlist
  copy:
    content: "{{ pacman_mirrorlist.content | regex_replace('#Server =', 'Server =') }}"
    dest: /etc/pacman.d/mirrorlist
    mode: 0644
  become: yes

- name: Install packages
  pacman:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ packages }}"
  become: yes

- name: Fetch zoom client package
  get_url:
    url: https://zoom.us/client/latest/zoom_x86_64.pkg.tar.xz
    dest: /tmp/zoom_x86_64.pkg.tar.xz
    mode: 0644

- name: Install zoom client
  command: pacman -U --noconfirm /tmp/zoom_x86_64.pkg.tar.xz
  become: yes

- name: Enable lightdm
  systemd:
    name: lightdm
    enabled: yes
  become: yes

