---
- name: Fetch dotfiles
  git:
    repo: ssh://git@github.com/mtpereira/dotfiles.git
    dest: "{{ ansible_user_dir }}/.dotfiles"
    version: master
    accept_hostkey: yes

- name: Install dotfiles
  command: "{{ ansible_user_dir }}/.dotfiles/install.sh"

- name: Create .desktop files directory
  file:
    path: "{{ ansible_user_dir }}/.local/share/applications/"
    state: directory

- name: Copy .desktop files
  synchronize:
    src: "desktop/"
    dest: "{{ ansible_user_dir }}/.local/share/applications/"

- name: Copy abcde config
  copy:
    src: "files/.abcde.conf"
    dest: "{{ ansible_user_dir }}/.abcde.conf"
    owner: "{{ ansible_user }}"
    mode: 0644
