---
- name: Install build dependencies
  pacman:
    name: "{{ aur_dependencies }}"
    state: present
  become: yes

- name: Install AUR helper dependencies
  pacman:
    name: "{{ aur_helper_dependencies[aur_helper] }}"
    state: present
  become: yes

- name: Check if the AUR helper {{ aur_helper }} is installed
  command: pacman -Q "{{ aur_helper }}"
  failed_when: no
  changed_when: no
  register: aur_helper_installed

- block:
  - name: Create the AUR build directory
    file:
      dest: "{{ aur_build_dir }}/{{ aur_helper }}"
      state: directory

  - name: Fetch the AUR helper {{ aur_helper }}
    get_url:
      url: "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h={{ aur_helper }}"
      dest: "{{ aur_build_dir }}/{{ aur_helper }}"

  - name: Install the AUR helper {{ aur_helper }}
    command: makepkg PKGBUILD --install --needed --noconfirm --noprogressbar
    args:
      chdir: "{{ aur_build_dir }}/{{ aur_helper }}/"
  when: aur_helper_installed.rc != 0

