---
- name: Install asdf
  block:
    - name: Clone the repository
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "{{ ansible_user_dir }}/.asdf"
        version: v0.7.6
        accept_hostkey: yes

    - name: Install plugins
      command: "asdf plugin-add {{ item }}"
      with_items: "{{ install_asdf_plugins }}"
      register: asdf_install_plugins_result
      failed_when: >
        (asdf_install_plugins_result.rc != 0)
        and (asdf_install_plugins_result.rc != 2)
      changed_when: asdf_install_plugins_result.rc != 2